algoritmo "contagemRegressiva"
// Função : Utilizar estrutura de repeticao para contar de 10 ate 0
// Autor : Viviane
// Data : 28/12/2021
// Seção de Declarações 
var
   contador : inteiro
inicio
      contador <- 10
      Enquanto (contador >= 0) faca
               EscrevaL (contador)
               contador <- contador - 1
      FimEnquanto
      EscrevaL ("Fim da contagem regressiva")
fimalgoritmo
