algoritmo "disney"
// Função :  Calcular a condição de ir para Disney
// Autor :  Viviane
// Data : 30/07/2021
// Seção de Declarações 
var
  dinheiro: real
inicio
      Escreva ("Quanto dinheiro eu tenho? ")
      leia (dinheiro)
      Se (dinheiro >= 10000) entao
         Escreva ("Partiu Disney!!!")
      Senao
           Escreva ("Preciso juntar mais dinheiro...")
      FimSe
fimalgoritmo
