algoritmo "funcoes-aritmeticas"
// Função : Funções aritméticas
// Autor :  Viviane
// Data : 27/07/2021
// Seção de Declarações 
var
   A: inteiro
   B: Real
   C: Real
inicio
      A <- Abs (-50)
      Escreval ("O número absoluto de -50 é ", A)
      B <- Exp (9,5)
      Escreval ("O expoente de 9 elevado a 5 é ", B)
      C <- RaizQ (81)
      Escreval ("A raiz quadrada de 81 é ", C)
      
fimalgoritmo
