algoritmo "nome-salario"
// Função :Mostrar o nome e o salário de um funcionário
// Autor : Viviane
// Data : 27/07/2021
// Seção de Declarações 
var
   nome: caractere
   salario: real
inicio
      Escreval ("Digite o nome do funcionário(a): ")
      leia (nome)
      Escreval ("Digite o salário do funcionário(a): ")
      leia (salario)
      Escreva ("O salário do funcinário ", nome, " é ", salario)
fimalgoritmo
