algoritmo "ParOuImpar"
// Função : Determinar se o número digitado é par ou impar
// Autor : Viviane
// Data : 30/07/2021
// Seção de Declarações 
var
   N: inteiro
inicio
      Escreva("Digite um número qualquer: ")
      Leia (N)
      Se (N % 2 = 0) entao
         Escreva ("O número ", N, " é PAR.")
      senao
           Escreva ("O número ", N, " é IMPAR.")
      FimSe
fimalgoritmo
